spring:
  datasource:
    url: jdbc:postgresql://dpg-cs8c7pm8ii6s73c83o8g-a.frankfurt-postgres.render.com:5432/db_56ab
    username: user
    password: lu79Mxoj4oQVSm1YK2D7L8rBVaFmkXk0
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

application:
  security:
    jwt:
      expiration: 43200000
      secret-key: jakistajnykluczglownydoaplikacjiwktorejjestrestauracjaiuzytkownikowieiichzamowieniaiwszystkoinneinformacjeiwszystkoinneinformacjei