spring:
  datasource:
    url: jdbc:postgresql://dpg-ct44cui3esus73fclfmg-a.frankfurt-postgres.render.com:5432/db_twrk
    username: user
    password: VQ3ljnZrj7wNS6uKeKngylVOObmMd9tH
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

application:
  security:
    jwt:
      expiration: 43200000
      secret-key: jakistajnykluczglownydoaplikacjiwktorejjestrestauracjaiuzytkownikowieiichzamowieniaiwszystkoinneinformacjeiwszystkoinneinformacjei