spring:
  datasource:
    url: jdbc:postgresql://dpg-cqtkfcdds78s739o4bg0-a.frankfurt-postgres.render.com:5432/restaurant_xwl4
    username: restaurant_xwl4_user
    password: K41jkw2Vobmrn6RqRQVQ9OYLZveK8H76
  jpa:
#    postgresql://:@/restaurant_xwl4
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

application:
  security:
    jwt:
      expiration: 43200000
      secret-key: jakistajnykluczglownydoaplikacjiwktorejjestrestauracjaiuzytkownikowieiichzamowieniaiwszystkoinneinformacjeiwszystkoinneinformacjei