spring:
  datasource:
    url: jdbc:postgresql://dpg-crhfgql6l47c73c82pe0-a.frankfurt-postgres.render.com:5432/new_zzlj
    username: new_zzlj_user
    password: nS24moNWPXxC2M7yeFhkUY51ku1FlGsP
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

application:
  security:
    jwt:
      expiration: 43200000
      secret-key: jakistajnykluczglownydoaplikacjiwktorejjestrestauracjaiuzytkownikowieiichzamowieniaiwszystkoinneinformacjeiwszystkoinneinformacjei